// Code generated by protoc-gen-go. DO NOT EDIT.
// source: library.proto

package library

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ListAuthorsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListAuthorsRequest) Reset()         { *m = ListAuthorsRequest{} }
func (m *ListAuthorsRequest) String() string { return proto.CompactTextString(m) }
func (*ListAuthorsRequest) ProtoMessage()    {}
func (*ListAuthorsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_library_94c080e219b34e5e, []int{0}
}
func (m *ListAuthorsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListAuthorsRequest.Unmarshal(m, b)
}
func (m *ListAuthorsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListAuthorsRequest.Marshal(b, m, deterministic)
}
func (dst *ListAuthorsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListAuthorsRequest.Merge(dst, src)
}
func (m *ListAuthorsRequest) XXX_Size() int {
	return xxx_messageInfo_ListAuthorsRequest.Size(m)
}
func (m *ListAuthorsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListAuthorsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListAuthorsRequest proto.InternalMessageInfo

type ListAuthorsResponse struct {
	AuthorId             int32    `protobuf:"varint,1,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	FirstName            string   `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string   `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListAuthorsResponse) Reset()         { *m = ListAuthorsResponse{} }
func (m *ListAuthorsResponse) String() string { return proto.CompactTextString(m) }
func (*ListAuthorsResponse) ProtoMessage()    {}
func (*ListAuthorsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_library_94c080e219b34e5e, []int{1}
}
func (m *ListAuthorsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListAuthorsResponse.Unmarshal(m, b)
}
func (m *ListAuthorsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListAuthorsResponse.Marshal(b, m, deterministic)
}
func (dst *ListAuthorsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListAuthorsResponse.Merge(dst, src)
}
func (m *ListAuthorsResponse) XXX_Size() int {
	return xxx_messageInfo_ListAuthorsResponse.Size(m)
}
func (m *ListAuthorsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListAuthorsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListAuthorsResponse proto.InternalMessageInfo

func (m *ListAuthorsResponse) GetAuthorId() int32 {
	if m != nil {
		return m.AuthorId
	}
	return 0
}

func (m *ListAuthorsResponse) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *ListAuthorsResponse) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

type ListPublishersRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListPublishersRequest) Reset()         { *m = ListPublishersRequest{} }
func (m *ListPublishersRequest) String() string { return proto.CompactTextString(m) }
func (*ListPublishersRequest) ProtoMessage()    {}
func (*ListPublishersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_library_94c080e219b34e5e, []int{2}
}
func (m *ListPublishersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPublishersRequest.Unmarshal(m, b)
}
func (m *ListPublishersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPublishersRequest.Marshal(b, m, deterministic)
}
func (dst *ListPublishersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPublishersRequest.Merge(dst, src)
}
func (m *ListPublishersRequest) XXX_Size() int {
	return xxx_messageInfo_ListPublishersRequest.Size(m)
}
func (m *ListPublishersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPublishersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListPublishersRequest proto.InternalMessageInfo

type ListPublishersResponse struct {
	PublisherId          int32    `protobuf:"varint,1,opt,name=publisher_id,json=publisherId,proto3" json:"publisher_id,omitempty"`
	PublisherName        string   `protobuf:"bytes,2,opt,name=publisher_name,json=publisherName,proto3" json:"publisher_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListPublishersResponse) Reset()         { *m = ListPublishersResponse{} }
func (m *ListPublishersResponse) String() string { return proto.CompactTextString(m) }
func (*ListPublishersResponse) ProtoMessage()    {}
func (*ListPublishersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_library_94c080e219b34e5e, []int{3}
}
func (m *ListPublishersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPublishersResponse.Unmarshal(m, b)
}
func (m *ListPublishersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPublishersResponse.Marshal(b, m, deterministic)
}
func (dst *ListPublishersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPublishersResponse.Merge(dst, src)
}
func (m *ListPublishersResponse) XXX_Size() int {
	return xxx_messageInfo_ListPublishersResponse.Size(m)
}
func (m *ListPublishersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPublishersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListPublishersResponse proto.InternalMessageInfo

func (m *ListPublishersResponse) GetPublisherId() int32 {
	if m != nil {
		return m.PublisherId
	}
	return 0
}

func (m *ListPublishersResponse) GetPublisherName() string {
	if m != nil {
		return m.PublisherName
	}
	return ""
}

type AddPublisherRequest struct {
	PublisherName        string   `protobuf:"bytes,1,opt,name=publisher_name,json=publisherName,proto3" json:"publisher_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddPublisherRequest) Reset()         { *m = AddPublisherRequest{} }
func (m *AddPublisherRequest) String() string { return proto.CompactTextString(m) }
func (*AddPublisherRequest) ProtoMessage()    {}
func (*AddPublisherRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_library_94c080e219b34e5e, []int{4}
}
func (m *AddPublisherRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddPublisherRequest.Unmarshal(m, b)
}
func (m *AddPublisherRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddPublisherRequest.Marshal(b, m, deterministic)
}
func (dst *AddPublisherRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddPublisherRequest.Merge(dst, src)
}
func (m *AddPublisherRequest) XXX_Size() int {
	return xxx_messageInfo_AddPublisherRequest.Size(m)
}
func (m *AddPublisherRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddPublisherRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddPublisherRequest proto.InternalMessageInfo

func (m *AddPublisherRequest) GetPublisherName() string {
	if m != nil {
		return m.PublisherName
	}
	return ""
}

type AddPublisherResponse struct {
	PublisherId          int32    `protobuf:"varint,1,opt,name=publisher_id,json=publisherId,proto3" json:"publisher_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddPublisherResponse) Reset()         { *m = AddPublisherResponse{} }
func (m *AddPublisherResponse) String() string { return proto.CompactTextString(m) }
func (*AddPublisherResponse) ProtoMessage()    {}
func (*AddPublisherResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_library_94c080e219b34e5e, []int{5}
}
func (m *AddPublisherResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddPublisherResponse.Unmarshal(m, b)
}
func (m *AddPublisherResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddPublisherResponse.Marshal(b, m, deterministic)
}
func (dst *AddPublisherResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddPublisherResponse.Merge(dst, src)
}
func (m *AddPublisherResponse) XXX_Size() int {
	return xxx_messageInfo_AddPublisherResponse.Size(m)
}
func (m *AddPublisherResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddPublisherResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddPublisherResponse proto.InternalMessageInfo

func (m *AddPublisherResponse) GetPublisherId() int32 {
	if m != nil {
		return m.PublisherId
	}
	return 0
}

type ListCurrentBookLoansRequest struct {
	BookId               int32    `protobuf:"varint,1,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListCurrentBookLoansRequest) Reset()         { *m = ListCurrentBookLoansRequest{} }
func (m *ListCurrentBookLoansRequest) String() string { return proto.CompactTextString(m) }
func (*ListCurrentBookLoansRequest) ProtoMessage()    {}
func (*ListCurrentBookLoansRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_library_94c080e219b34e5e, []int{6}
}
func (m *ListCurrentBookLoansRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListCurrentBookLoansRequest.Unmarshal(m, b)
}
func (m *ListCurrentBookLoansRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListCurrentBookLoansRequest.Marshal(b, m, deterministic)
}
func (dst *ListCurrentBookLoansRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListCurrentBookLoansRequest.Merge(dst, src)
}
func (m *ListCurrentBookLoansRequest) XXX_Size() int {
	return xxx_messageInfo_ListCurrentBookLoansRequest.Size(m)
}
func (m *ListCurrentBookLoansRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListCurrentBookLoansRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListCurrentBookLoansRequest proto.InternalMessageInfo

func (m *ListCurrentBookLoansRequest) GetBookId() int32 {
	if m != nil {
		return m.BookId
	}
	return 0
}

type ListCurrentBookLoansResponse struct {
	LoanId               int32                `protobuf:"varint,1,opt,name=loan_id,json=loanId,proto3" json:"loan_id,omitempty"`
	UserName             string               `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	Email                string               `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	LoanDate             *timestamp.Timestamp `protobuf:"bytes,4,opt,name=loan_date,json=loanDate,proto3" json:"loan_date,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ListCurrentBookLoansResponse) Reset()         { *m = ListCurrentBookLoansResponse{} }
func (m *ListCurrentBookLoansResponse) String() string { return proto.CompactTextString(m) }
func (*ListCurrentBookLoansResponse) ProtoMessage()    {}
func (*ListCurrentBookLoansResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_library_94c080e219b34e5e, []int{7}
}
func (m *ListCurrentBookLoansResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListCurrentBookLoansResponse.Unmarshal(m, b)
}
func (m *ListCurrentBookLoansResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListCurrentBookLoansResponse.Marshal(b, m, deterministic)
}
func (dst *ListCurrentBookLoansResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListCurrentBookLoansResponse.Merge(dst, src)
}
func (m *ListCurrentBookLoansResponse) XXX_Size() int {
	return xxx_messageInfo_ListCurrentBookLoansResponse.Size(m)
}
func (m *ListCurrentBookLoansResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListCurrentBookLoansResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListCurrentBookLoansResponse proto.InternalMessageInfo

func (m *ListCurrentBookLoansResponse) GetLoanId() int32 {
	if m != nil {
		return m.LoanId
	}
	return 0
}

func (m *ListCurrentBookLoansResponse) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *ListCurrentBookLoansResponse) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *ListCurrentBookLoansResponse) GetLoanDate() *timestamp.Timestamp {
	if m != nil {
		return m.LoanDate
	}
	return nil
}

type Author struct {
	FirstName            string   `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string   `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Author) Reset()         { *m = Author{} }
func (m *Author) String() string { return proto.CompactTextString(m) }
func (*Author) ProtoMessage()    {}
func (*Author) Descriptor() ([]byte, []int) {
	return fileDescriptor_library_94c080e219b34e5e, []int{8}
}
func (m *Author) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Author.Unmarshal(m, b)
}
func (m *Author) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Author.Marshal(b, m, deterministic)
}
func (dst *Author) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Author.Merge(dst, src)
}
func (m *Author) XXX_Size() int {
	return xxx_messageInfo_Author.Size(m)
}
func (m *Author) XXX_DiscardUnknown() {
	xxx_messageInfo_Author.DiscardUnknown(m)
}

var xxx_messageInfo_Author proto.InternalMessageInfo

func (m *Author) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *Author) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

type AddBookRequest struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Authors              []int32  `protobuf:"varint,2,rep,packed,name=authors,proto3" json:"authors,omitempty"`
	PublisherId          int32    `protobuf:"varint,3,opt,name=publisher_id,json=publisherId,proto3" json:"publisher_id,omitempty"`
	Copies               int32    `protobuf:"varint,4,opt,name=copies,proto3" json:"copies,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddBookRequest) Reset()         { *m = AddBookRequest{} }
func (m *AddBookRequest) String() string { return proto.CompactTextString(m) }
func (*AddBookRequest) ProtoMessage()    {}
func (*AddBookRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_library_94c080e219b34e5e, []int{9}
}
func (m *AddBookRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddBookRequest.Unmarshal(m, b)
}
func (m *AddBookRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddBookRequest.Marshal(b, m, deterministic)
}
func (dst *AddBookRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddBookRequest.Merge(dst, src)
}
func (m *AddBookRequest) XXX_Size() int {
	return xxx_messageInfo_AddBookRequest.Size(m)
}
func (m *AddBookRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddBookRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddBookRequest proto.InternalMessageInfo

func (m *AddBookRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *AddBookRequest) GetAuthors() []int32 {
	if m != nil {
		return m.Authors
	}
	return nil
}

func (m *AddBookRequest) GetPublisherId() int32 {
	if m != nil {
		return m.PublisherId
	}
	return 0
}

func (m *AddBookRequest) GetCopies() int32 {
	if m != nil {
		return m.Copies
	}
	return 0
}

type AddBookResponse struct {
	BookId               int32    `protobuf:"varint,1,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddBookResponse) Reset()         { *m = AddBookResponse{} }
func (m *AddBookResponse) String() string { return proto.CompactTextString(m) }
func (*AddBookResponse) ProtoMessage()    {}
func (*AddBookResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_library_94c080e219b34e5e, []int{10}
}
func (m *AddBookResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddBookResponse.Unmarshal(m, b)
}
func (m *AddBookResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddBookResponse.Marshal(b, m, deterministic)
}
func (dst *AddBookResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddBookResponse.Merge(dst, src)
}
func (m *AddBookResponse) XXX_Size() int {
	return xxx_messageInfo_AddBookResponse.Size(m)
}
func (m *AddBookResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddBookResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddBookResponse proto.InternalMessageInfo

func (m *AddBookResponse) GetBookId() int32 {
	if m != nil {
		return m.BookId
	}
	return 0
}

type GetBookRequest struct {
	BookId               int32    `protobuf:"varint,1,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBookRequest) Reset()         { *m = GetBookRequest{} }
func (m *GetBookRequest) String() string { return proto.CompactTextString(m) }
func (*GetBookRequest) ProtoMessage()    {}
func (*GetBookRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_library_94c080e219b34e5e, []int{11}
}
func (m *GetBookRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBookRequest.Unmarshal(m, b)
}
func (m *GetBookRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBookRequest.Marshal(b, m, deterministic)
}
func (dst *GetBookRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBookRequest.Merge(dst, src)
}
func (m *GetBookRequest) XXX_Size() int {
	return xxx_messageInfo_GetBookRequest.Size(m)
}
func (m *GetBookRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBookRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBookRequest proto.InternalMessageInfo

func (m *GetBookRequest) GetBookId() int32 {
	if m != nil {
		return m.BookId
	}
	return 0
}

type GetBookResponse struct {
	BookId               int32     `protobuf:"varint,1,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	BookTitle            string    `protobuf:"bytes,2,opt,name=book_title,json=bookTitle,proto3" json:"book_title,omitempty"`
	Authors              []*Author `protobuf:"bytes,3,rep,name=authors,proto3" json:"authors,omitempty"`
	AvailableCopies      int32     `protobuf:"varint,4,opt,name=available_copies,json=availableCopies,proto3" json:"available_copies,omitempty"`
	LoanedCopies         int32     `protobuf:"varint,5,opt,name=loaned_copies,json=loanedCopies,proto3" json:"loaned_copies,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetBookResponse) Reset()         { *m = GetBookResponse{} }
func (m *GetBookResponse) String() string { return proto.CompactTextString(m) }
func (*GetBookResponse) ProtoMessage()    {}
func (*GetBookResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_library_94c080e219b34e5e, []int{12}
}
func (m *GetBookResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBookResponse.Unmarshal(m, b)
}
func (m *GetBookResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBookResponse.Marshal(b, m, deterministic)
}
func (dst *GetBookResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBookResponse.Merge(dst, src)
}
func (m *GetBookResponse) XXX_Size() int {
	return xxx_messageInfo_GetBookResponse.Size(m)
}
func (m *GetBookResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBookResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetBookResponse proto.InternalMessageInfo

func (m *GetBookResponse) GetBookId() int32 {
	if m != nil {
		return m.BookId
	}
	return 0
}

func (m *GetBookResponse) GetBookTitle() string {
	if m != nil {
		return m.BookTitle
	}
	return ""
}

func (m *GetBookResponse) GetAuthors() []*Author {
	if m != nil {
		return m.Authors
	}
	return nil
}

func (m *GetBookResponse) GetAvailableCopies() int32 {
	if m != nil {
		return m.AvailableCopies
	}
	return 0
}

func (m *GetBookResponse) GetLoanedCopies() int32 {
	if m != nil {
		return m.LoanedCopies
	}
	return 0
}

type ListBooksRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListBooksRequest) Reset()         { *m = ListBooksRequest{} }
func (m *ListBooksRequest) String() string { return proto.CompactTextString(m) }
func (*ListBooksRequest) ProtoMessage()    {}
func (*ListBooksRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_library_94c080e219b34e5e, []int{13}
}
func (m *ListBooksRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListBooksRequest.Unmarshal(m, b)
}
func (m *ListBooksRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListBooksRequest.Marshal(b, m, deterministic)
}
func (dst *ListBooksRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListBooksRequest.Merge(dst, src)
}
func (m *ListBooksRequest) XXX_Size() int {
	return xxx_messageInfo_ListBooksRequest.Size(m)
}
func (m *ListBooksRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListBooksRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListBooksRequest proto.InternalMessageInfo

type ListBooksResponse struct {
	BookId               int32     `protobuf:"varint,1,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	BookTitle            string    `protobuf:"bytes,2,opt,name=book_title,json=bookTitle,proto3" json:"book_title,omitempty"`
	Authors              []*Author `protobuf:"bytes,3,rep,name=authors,proto3" json:"authors,omitempty"`
	AvailableCopies      int32     `protobuf:"varint,4,opt,name=available_copies,json=availableCopies,proto3" json:"available_copies,omitempty"`
	LoanedCopies         int32     `protobuf:"varint,5,opt,name=loaned_copies,json=loanedCopies,proto3" json:"loaned_copies,omitempty"`
	PublisherName        string    `protobuf:"bytes,6,opt,name=publisher_name,json=publisherName,proto3" json:"publisher_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ListBooksResponse) Reset()         { *m = ListBooksResponse{} }
func (m *ListBooksResponse) String() string { return proto.CompactTextString(m) }
func (*ListBooksResponse) ProtoMessage()    {}
func (*ListBooksResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_library_94c080e219b34e5e, []int{14}
}
func (m *ListBooksResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListBooksResponse.Unmarshal(m, b)
}
func (m *ListBooksResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListBooksResponse.Marshal(b, m, deterministic)
}
func (dst *ListBooksResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListBooksResponse.Merge(dst, src)
}
func (m *ListBooksResponse) XXX_Size() int {
	return xxx_messageInfo_ListBooksResponse.Size(m)
}
func (m *ListBooksResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListBooksResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListBooksResponse proto.InternalMessageInfo

func (m *ListBooksResponse) GetBookId() int32 {
	if m != nil {
		return m.BookId
	}
	return 0
}

func (m *ListBooksResponse) GetBookTitle() string {
	if m != nil {
		return m.BookTitle
	}
	return ""
}

func (m *ListBooksResponse) GetAuthors() []*Author {
	if m != nil {
		return m.Authors
	}
	return nil
}

func (m *ListBooksResponse) GetAvailableCopies() int32 {
	if m != nil {
		return m.AvailableCopies
	}
	return 0
}

func (m *ListBooksResponse) GetLoanedCopies() int32 {
	if m != nil {
		return m.LoanedCopies
	}
	return 0
}

func (m *ListBooksResponse) GetPublisherName() string {
	if m != nil {
		return m.PublisherName
	}
	return ""
}

type AddAuthorRequest struct {
	FirstName            string   `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string   `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddAuthorRequest) Reset()         { *m = AddAuthorRequest{} }
func (m *AddAuthorRequest) String() string { return proto.CompactTextString(m) }
func (*AddAuthorRequest) ProtoMessage()    {}
func (*AddAuthorRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_library_94c080e219b34e5e, []int{15}
}
func (m *AddAuthorRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddAuthorRequest.Unmarshal(m, b)
}
func (m *AddAuthorRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddAuthorRequest.Marshal(b, m, deterministic)
}
func (dst *AddAuthorRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddAuthorRequest.Merge(dst, src)
}
func (m *AddAuthorRequest) XXX_Size() int {
	return xxx_messageInfo_AddAuthorRequest.Size(m)
}
func (m *AddAuthorRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddAuthorRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddAuthorRequest proto.InternalMessageInfo

func (m *AddAuthorRequest) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *AddAuthorRequest) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

type AddAuthorResponse struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddAuthorResponse) Reset()         { *m = AddAuthorResponse{} }
func (m *AddAuthorResponse) String() string { return proto.CompactTextString(m) }
func (*AddAuthorResponse) ProtoMessage()    {}
func (*AddAuthorResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_library_94c080e219b34e5e, []int{16}
}
func (m *AddAuthorResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddAuthorResponse.Unmarshal(m, b)
}
func (m *AddAuthorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddAuthorResponse.Marshal(b, m, deterministic)
}
func (dst *AddAuthorResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddAuthorResponse.Merge(dst, src)
}
func (m *AddAuthorResponse) XXX_Size() int {
	return xxx_messageInfo_AddAuthorResponse.Size(m)
}
func (m *AddAuthorResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddAuthorResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddAuthorResponse proto.InternalMessageInfo

func (m *AddAuthorResponse) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type LoanBookRequest struct {
	BookId               int32    `protobuf:"varint,1,opt,name=book_id,json=bookId,proto3" json:"book_id,omitempty"`
	UserId               int32    `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoanBookRequest) Reset()         { *m = LoanBookRequest{} }
func (m *LoanBookRequest) String() string { return proto.CompactTextString(m) }
func (*LoanBookRequest) ProtoMessage()    {}
func (*LoanBookRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_library_94c080e219b34e5e, []int{17}
}
func (m *LoanBookRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoanBookRequest.Unmarshal(m, b)
}
func (m *LoanBookRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoanBookRequest.Marshal(b, m, deterministic)
}
func (dst *LoanBookRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoanBookRequest.Merge(dst, src)
}
func (m *LoanBookRequest) XXX_Size() int {
	return xxx_messageInfo_LoanBookRequest.Size(m)
}
func (m *LoanBookRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoanBookRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoanBookRequest proto.InternalMessageInfo

func (m *LoanBookRequest) GetBookId() int32 {
	if m != nil {
		return m.BookId
	}
	return 0
}

func (m *LoanBookRequest) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type LoanBookResponse struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoanBookResponse) Reset()         { *m = LoanBookResponse{} }
func (m *LoanBookResponse) String() string { return proto.CompactTextString(m) }
func (*LoanBookResponse) ProtoMessage()    {}
func (*LoanBookResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_library_94c080e219b34e5e, []int{18}
}
func (m *LoanBookResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoanBookResponse.Unmarshal(m, b)
}
func (m *LoanBookResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoanBookResponse.Marshal(b, m, deterministic)
}
func (dst *LoanBookResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoanBookResponse.Merge(dst, src)
}
func (m *LoanBookResponse) XXX_Size() int {
	return xxx_messageInfo_LoanBookResponse.Size(m)
}
func (m *LoanBookResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoanBookResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoanBookResponse proto.InternalMessageInfo

func (m *LoanBookResponse) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type ReturnBookRequest struct {
	LoanId               int32    `protobuf:"varint,1,opt,name=loan_id,json=loanId,proto3" json:"loan_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReturnBookRequest) Reset()         { *m = ReturnBookRequest{} }
func (m *ReturnBookRequest) String() string { return proto.CompactTextString(m) }
func (*ReturnBookRequest) ProtoMessage()    {}
func (*ReturnBookRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_library_94c080e219b34e5e, []int{19}
}
func (m *ReturnBookRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReturnBookRequest.Unmarshal(m, b)
}
func (m *ReturnBookRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReturnBookRequest.Marshal(b, m, deterministic)
}
func (dst *ReturnBookRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReturnBookRequest.Merge(dst, src)
}
func (m *ReturnBookRequest) XXX_Size() int {
	return xxx_messageInfo_ReturnBookRequest.Size(m)
}
func (m *ReturnBookRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReturnBookRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReturnBookRequest proto.InternalMessageInfo

func (m *ReturnBookRequest) GetLoanId() int32 {
	if m != nil {
		return m.LoanId
	}
	return 0
}

type ReturnBookResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReturnBookResponse) Reset()         { *m = ReturnBookResponse{} }
func (m *ReturnBookResponse) String() string { return proto.CompactTextString(m) }
func (*ReturnBookResponse) ProtoMessage()    {}
func (*ReturnBookResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_library_94c080e219b34e5e, []int{20}
}
func (m *ReturnBookResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReturnBookResponse.Unmarshal(m, b)
}
func (m *ReturnBookResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReturnBookResponse.Marshal(b, m, deterministic)
}
func (dst *ReturnBookResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReturnBookResponse.Merge(dst, src)
}
func (m *ReturnBookResponse) XXX_Size() int {
	return xxx_messageInfo_ReturnBookResponse.Size(m)
}
func (m *ReturnBookResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReturnBookResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReturnBookResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*ListAuthorsRequest)(nil), "library.ListAuthorsRequest")
	proto.RegisterType((*ListAuthorsResponse)(nil), "library.ListAuthorsResponse")
	proto.RegisterType((*ListPublishersRequest)(nil), "library.ListPublishersRequest")
	proto.RegisterType((*ListPublishersResponse)(nil), "library.ListPublishersResponse")
	proto.RegisterType((*AddPublisherRequest)(nil), "library.AddPublisherRequest")
	proto.RegisterType((*AddPublisherResponse)(nil), "library.AddPublisherResponse")
	proto.RegisterType((*ListCurrentBookLoansRequest)(nil), "library.ListCurrentBookLoansRequest")
	proto.RegisterType((*ListCurrentBookLoansResponse)(nil), "library.ListCurrentBookLoansResponse")
	proto.RegisterType((*Author)(nil), "library.Author")
	proto.RegisterType((*AddBookRequest)(nil), "library.AddBookRequest")
	proto.RegisterType((*AddBookResponse)(nil), "library.AddBookResponse")
	proto.RegisterType((*GetBookRequest)(nil), "library.GetBookRequest")
	proto.RegisterType((*GetBookResponse)(nil), "library.GetBookResponse")
	proto.RegisterType((*ListBooksRequest)(nil), "library.ListBooksRequest")
	proto.RegisterType((*ListBooksResponse)(nil), "library.ListBooksResponse")
	proto.RegisterType((*AddAuthorRequest)(nil), "library.AddAuthorRequest")
	proto.RegisterType((*AddAuthorResponse)(nil), "library.AddAuthorResponse")
	proto.RegisterType((*LoanBookRequest)(nil), "library.LoanBookRequest")
	proto.RegisterType((*LoanBookResponse)(nil), "library.LoanBookResponse")
	proto.RegisterType((*ReturnBookRequest)(nil), "library.ReturnBookRequest")
	proto.RegisterType((*ReturnBookResponse)(nil), "library.ReturnBookResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// LibraryServiceClient is the client API for LibraryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LibraryServiceClient interface {
	AddBook(ctx context.Context, in *AddBookRequest, opts ...grpc.CallOption) (*AddBookResponse, error)
	GetBook(ctx context.Context, in *GetBookRequest, opts ...grpc.CallOption) (*GetBookResponse, error)
	ListBooks(ctx context.Context, in *ListBooksRequest, opts ...grpc.CallOption) (LibraryService_ListBooksClient, error)
	AddAuthor(ctx context.Context, in *AddAuthorRequest, opts ...grpc.CallOption) (*AddAuthorResponse, error)
	ListAuthors(ctx context.Context, in *ListAuthorsRequest, opts ...grpc.CallOption) (LibraryService_ListAuthorsClient, error)
	LoanBook(ctx context.Context, in *LoanBookRequest, opts ...grpc.CallOption) (*LoanBookResponse, error)
	ReturnBook(ctx context.Context, in *ReturnBookRequest, opts ...grpc.CallOption) (*ReturnBookResponse, error)
	ListCurrentBookLoans(ctx context.Context, in *ListCurrentBookLoansRequest, opts ...grpc.CallOption) (LibraryService_ListCurrentBookLoansClient, error)
	ListPublishers(ctx context.Context, in *ListPublishersRequest, opts ...grpc.CallOption) (LibraryService_ListPublishersClient, error)
	AddPublisher(ctx context.Context, in *AddPublisherRequest, opts ...grpc.CallOption) (*AddPublisherResponse, error)
}

type libraryServiceClient struct {
	cc *grpc.ClientConn
}

func NewLibraryServiceClient(cc *grpc.ClientConn) LibraryServiceClient {
	return &libraryServiceClient{cc}
}

func (c *libraryServiceClient) AddBook(ctx context.Context, in *AddBookRequest, opts ...grpc.CallOption) (*AddBookResponse, error) {
	out := new(AddBookResponse)
	err := c.cc.Invoke(ctx, "/library.LibraryService/AddBook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *libraryServiceClient) GetBook(ctx context.Context, in *GetBookRequest, opts ...grpc.CallOption) (*GetBookResponse, error) {
	out := new(GetBookResponse)
	err := c.cc.Invoke(ctx, "/library.LibraryService/GetBook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *libraryServiceClient) ListBooks(ctx context.Context, in *ListBooksRequest, opts ...grpc.CallOption) (LibraryService_ListBooksClient, error) {
	stream, err := c.cc.NewStream(ctx, &_LibraryService_serviceDesc.Streams[0], "/library.LibraryService/ListBooks", opts...)
	if err != nil {
		return nil, err
	}
	x := &libraryServiceListBooksClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type LibraryService_ListBooksClient interface {
	Recv() (*ListBooksResponse, error)
	grpc.ClientStream
}

type libraryServiceListBooksClient struct {
	grpc.ClientStream
}

func (x *libraryServiceListBooksClient) Recv() (*ListBooksResponse, error) {
	m := new(ListBooksResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *libraryServiceClient) AddAuthor(ctx context.Context, in *AddAuthorRequest, opts ...grpc.CallOption) (*AddAuthorResponse, error) {
	out := new(AddAuthorResponse)
	err := c.cc.Invoke(ctx, "/library.LibraryService/AddAuthor", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *libraryServiceClient) ListAuthors(ctx context.Context, in *ListAuthorsRequest, opts ...grpc.CallOption) (LibraryService_ListAuthorsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_LibraryService_serviceDesc.Streams[1], "/library.LibraryService/ListAuthors", opts...)
	if err != nil {
		return nil, err
	}
	x := &libraryServiceListAuthorsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type LibraryService_ListAuthorsClient interface {
	Recv() (*ListAuthorsResponse, error)
	grpc.ClientStream
}

type libraryServiceListAuthorsClient struct {
	grpc.ClientStream
}

func (x *libraryServiceListAuthorsClient) Recv() (*ListAuthorsResponse, error) {
	m := new(ListAuthorsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *libraryServiceClient) LoanBook(ctx context.Context, in *LoanBookRequest, opts ...grpc.CallOption) (*LoanBookResponse, error) {
	out := new(LoanBookResponse)
	err := c.cc.Invoke(ctx, "/library.LibraryService/LoanBook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *libraryServiceClient) ReturnBook(ctx context.Context, in *ReturnBookRequest, opts ...grpc.CallOption) (*ReturnBookResponse, error) {
	out := new(ReturnBookResponse)
	err := c.cc.Invoke(ctx, "/library.LibraryService/ReturnBook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *libraryServiceClient) ListCurrentBookLoans(ctx context.Context, in *ListCurrentBookLoansRequest, opts ...grpc.CallOption) (LibraryService_ListCurrentBookLoansClient, error) {
	stream, err := c.cc.NewStream(ctx, &_LibraryService_serviceDesc.Streams[2], "/library.LibraryService/ListCurrentBookLoans", opts...)
	if err != nil {
		return nil, err
	}
	x := &libraryServiceListCurrentBookLoansClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type LibraryService_ListCurrentBookLoansClient interface {
	Recv() (*ListCurrentBookLoansResponse, error)
	grpc.ClientStream
}

type libraryServiceListCurrentBookLoansClient struct {
	grpc.ClientStream
}

func (x *libraryServiceListCurrentBookLoansClient) Recv() (*ListCurrentBookLoansResponse, error) {
	m := new(ListCurrentBookLoansResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *libraryServiceClient) ListPublishers(ctx context.Context, in *ListPublishersRequest, opts ...grpc.CallOption) (LibraryService_ListPublishersClient, error) {
	stream, err := c.cc.NewStream(ctx, &_LibraryService_serviceDesc.Streams[3], "/library.LibraryService/ListPublishers", opts...)
	if err != nil {
		return nil, err
	}
	x := &libraryServiceListPublishersClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type LibraryService_ListPublishersClient interface {
	Recv() (*ListPublishersResponse, error)
	grpc.ClientStream
}

type libraryServiceListPublishersClient struct {
	grpc.ClientStream
}

func (x *libraryServiceListPublishersClient) Recv() (*ListPublishersResponse, error) {
	m := new(ListPublishersResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *libraryServiceClient) AddPublisher(ctx context.Context, in *AddPublisherRequest, opts ...grpc.CallOption) (*AddPublisherResponse, error) {
	out := new(AddPublisherResponse)
	err := c.cc.Invoke(ctx, "/library.LibraryService/AddPublisher", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LibraryServiceServer is the server API for LibraryService service.
type LibraryServiceServer interface {
	AddBook(context.Context, *AddBookRequest) (*AddBookResponse, error)
	GetBook(context.Context, *GetBookRequest) (*GetBookResponse, error)
	ListBooks(*ListBooksRequest, LibraryService_ListBooksServer) error
	AddAuthor(context.Context, *AddAuthorRequest) (*AddAuthorResponse, error)
	ListAuthors(*ListAuthorsRequest, LibraryService_ListAuthorsServer) error
	LoanBook(context.Context, *LoanBookRequest) (*LoanBookResponse, error)
	ReturnBook(context.Context, *ReturnBookRequest) (*ReturnBookResponse, error)
	ListCurrentBookLoans(*ListCurrentBookLoansRequest, LibraryService_ListCurrentBookLoansServer) error
	ListPublishers(*ListPublishersRequest, LibraryService_ListPublishersServer) error
	AddPublisher(context.Context, *AddPublisherRequest) (*AddPublisherResponse, error)
}

func RegisterLibraryServiceServer(s *grpc.Server, srv LibraryServiceServer) {
	s.RegisterService(&_LibraryService_serviceDesc, srv)
}

func _LibraryService_AddBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddBookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LibraryServiceServer).AddBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/library.LibraryService/AddBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LibraryServiceServer).AddBook(ctx, req.(*AddBookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LibraryService_GetBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LibraryServiceServer).GetBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/library.LibraryService/GetBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LibraryServiceServer).GetBook(ctx, req.(*GetBookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LibraryService_ListBooks_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListBooksRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LibraryServiceServer).ListBooks(m, &libraryServiceListBooksServer{stream})
}

type LibraryService_ListBooksServer interface {
	Send(*ListBooksResponse) error
	grpc.ServerStream
}

type libraryServiceListBooksServer struct {
	grpc.ServerStream
}

func (x *libraryServiceListBooksServer) Send(m *ListBooksResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _LibraryService_AddAuthor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddAuthorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LibraryServiceServer).AddAuthor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/library.LibraryService/AddAuthor",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LibraryServiceServer).AddAuthor(ctx, req.(*AddAuthorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LibraryService_ListAuthors_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListAuthorsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LibraryServiceServer).ListAuthors(m, &libraryServiceListAuthorsServer{stream})
}

type LibraryService_ListAuthorsServer interface {
	Send(*ListAuthorsResponse) error
	grpc.ServerStream
}

type libraryServiceListAuthorsServer struct {
	grpc.ServerStream
}

func (x *libraryServiceListAuthorsServer) Send(m *ListAuthorsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _LibraryService_LoanBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoanBookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LibraryServiceServer).LoanBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/library.LibraryService/LoanBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LibraryServiceServer).LoanBook(ctx, req.(*LoanBookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LibraryService_ReturnBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReturnBookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LibraryServiceServer).ReturnBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/library.LibraryService/ReturnBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LibraryServiceServer).ReturnBook(ctx, req.(*ReturnBookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LibraryService_ListCurrentBookLoans_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListCurrentBookLoansRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LibraryServiceServer).ListCurrentBookLoans(m, &libraryServiceListCurrentBookLoansServer{stream})
}

type LibraryService_ListCurrentBookLoansServer interface {
	Send(*ListCurrentBookLoansResponse) error
	grpc.ServerStream
}

type libraryServiceListCurrentBookLoansServer struct {
	grpc.ServerStream
}

func (x *libraryServiceListCurrentBookLoansServer) Send(m *ListCurrentBookLoansResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _LibraryService_ListPublishers_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListPublishersRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LibraryServiceServer).ListPublishers(m, &libraryServiceListPublishersServer{stream})
}

type LibraryService_ListPublishersServer interface {
	Send(*ListPublishersResponse) error
	grpc.ServerStream
}

type libraryServiceListPublishersServer struct {
	grpc.ServerStream
}

func (x *libraryServiceListPublishersServer) Send(m *ListPublishersResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _LibraryService_AddPublisher_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddPublisherRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LibraryServiceServer).AddPublisher(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/library.LibraryService/AddPublisher",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LibraryServiceServer).AddPublisher(ctx, req.(*AddPublisherRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _LibraryService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "library.LibraryService",
	HandlerType: (*LibraryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddBook",
			Handler:    _LibraryService_AddBook_Handler,
		},
		{
			MethodName: "GetBook",
			Handler:    _LibraryService_GetBook_Handler,
		},
		{
			MethodName: "AddAuthor",
			Handler:    _LibraryService_AddAuthor_Handler,
		},
		{
			MethodName: "LoanBook",
			Handler:    _LibraryService_LoanBook_Handler,
		},
		{
			MethodName: "ReturnBook",
			Handler:    _LibraryService_ReturnBook_Handler,
		},
		{
			MethodName: "AddPublisher",
			Handler:    _LibraryService_AddPublisher_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListBooks",
			Handler:       _LibraryService_ListBooks_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ListAuthors",
			Handler:       _LibraryService_ListAuthors_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ListCurrentBookLoans",
			Handler:       _LibraryService_ListCurrentBookLoans_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ListPublishers",
			Handler:       _LibraryService_ListPublishers_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "library.proto",
}

func init() { proto.RegisterFile("library.proto", fileDescriptor_library_94c080e219b34e5e) }

var fileDescriptor_library_94c080e219b34e5e = []byte{
	// 791 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x56, 0xed, 0x4e, 0x13, 0x4d,
	0x14, 0x66, 0xdb, 0xb7, 0x5f, 0xa7, 0xd0, 0x96, 0xa1, 0x2f, 0x2d, 0x5b, 0x90, 0x3a, 0x48, 0x52,
	0x8c, 0x29, 0x06, 0x13, 0x8d, 0x89, 0x31, 0xa9, 0x10, 0x49, 0x93, 0x4a, 0xcc, 0x8a, 0xbf, 0xc9,
	0x94, 0x19, 0x60, 0xc3, 0xb6, 0x5b, 0x77, 0xa7, 0x24, 0xc6, 0x0b, 0xf0, 0x42, 0xbc, 0x15, 0x6f,
	0xc7, 0x7b, 0x30, 0x33, 0xb3, 0x1f, 0xb3, 0xdb, 0xad, 0x90, 0xf8, 0xcb, 0x9f, 0xe7, 0x39, 0xdf,
	0xe7, 0x3c, 0x67, 0x67, 0x61, 0xcd, 0xb1, 0xc7, 0x1e, 0xf1, 0xbe, 0xf6, 0x67, 0x9e, 0xcb, 0x5d,
	0x54, 0x0a, 0x44, 0x73, 0xf7, 0xda, 0x75, 0xaf, 0x1d, 0x76, 0x28, 0xe1, 0xf1, 0xfc, 0xea, 0x90,
	0xdb, 0x13, 0xe6, 0x73, 0x32, 0x99, 0x29, 0x4b, 0xdc, 0x04, 0x34, 0xb2, 0x7d, 0x3e, 0x98, 0xf3,
	0x1b, 0xd7, 0xf3, 0x2d, 0xf6, 0x65, 0xce, 0x7c, 0x8e, 0xa7, 0xb0, 0x91, 0x40, 0xfd, 0x99, 0x3b,
	0xf5, 0x19, 0xea, 0x40, 0x85, 0x48, 0xe8, 0xc2, 0xa6, 0x6d, 0xa3, 0x6b, 0xf4, 0x0a, 0x56, 0x59,
	0x01, 0x43, 0x8a, 0x76, 0x00, 0xae, 0x6c, 0xcf, 0xe7, 0x17, 0x53, 0x32, 0x61, 0xed, 0x5c, 0xd7,
	0xe8, 0x55, 0xac, 0x8a, 0x44, 0xce, 0xc8, 0x44, 0xfa, 0x3a, 0x24, 0xd4, 0xe6, 0xa5, 0xb6, 0x2c,
	0x00, 0xa1, 0xc4, 0x2d, 0xf8, 0x5f, 0xe4, 0xfb, 0x38, 0x1f, 0x3b, 0xb6, 0x7f, 0xc3, 0xe2, 0x42,
	0xc6, 0xb0, 0x99, 0x56, 0x04, 0xb5, 0x3c, 0x86, 0xd5, 0x59, 0x88, 0xc6, 0xe5, 0x54, 0x23, 0x6c,
	0x48, 0xd1, 0x3e, 0xd4, 0x62, 0x13, 0xad, 0xaa, 0xb5, 0x08, 0x95, 0xc9, 0xdf, 0xc0, 0xc6, 0x80,
	0xd2, 0x28, 0x45, 0x90, 0x3a, 0xc3, 0xdb, 0xc8, 0xf2, 0x7e, 0x0d, 0xcd, 0xa4, 0xf7, 0x83, 0xeb,
	0xc3, 0x2f, 0xa1, 0x23, 0x9a, 0x3b, 0x9e, 0x7b, 0x1e, 0x9b, 0xf2, 0x77, 0xae, 0x7b, 0x3b, 0x72,
	0xc9, 0x34, 0xec, 0x1d, 0xb5, 0xa0, 0x34, 0x76, 0xdd, 0xdb, 0xd8, 0xb9, 0x28, 0xc4, 0x21, 0xc5,
	0x3f, 0x0c, 0xd8, 0xce, 0x76, 0x0c, 0x72, 0xb7, 0xa0, 0xe4, 0xb8, 0x64, 0xaa, 0x79, 0x0a, 0x71,
	0x48, 0xc5, 0x12, 0xe6, 0x7e, 0x72, 0x18, 0x65, 0x01, 0xc8, 0x0d, 0x35, 0xa1, 0xc0, 0x26, 0xc4,
	0x76, 0x82, 0xed, 0x28, 0x01, 0xbd, 0x82, 0x8a, 0x8c, 0x45, 0x09, 0x67, 0xed, 0xff, 0xba, 0x46,
	0xaf, 0x7a, 0x64, 0xf6, 0x15, 0xab, 0xfa, 0x21, 0xab, 0xfa, 0xe7, 0x21, 0xab, 0xac, 0xb2, 0x30,
	0x3e, 0x21, 0x9c, 0xe1, 0x13, 0x28, 0x2a, 0xfe, 0xa4, 0x98, 0x61, 0xfc, 0x91, 0x19, 0xb9, 0x14,
	0x33, 0xbe, 0x41, 0x6d, 0x40, 0xa9, 0x68, 0x31, 0x1c, 0x4b, 0x13, 0x0a, 0xdc, 0xe6, 0x4e, 0x18,
	0x48, 0x09, 0xa8, 0x0d, 0x25, 0xc5, 0x44, 0xbf, 0x9d, 0xeb, 0xe6, 0x7b, 0x05, 0x2b, 0x14, 0x17,
	0x16, 0x91, 0x5f, 0x24, 0xca, 0x26, 0x14, 0x2f, 0xdd, 0x99, 0xcd, 0x7c, 0xd9, 0x60, 0xc1, 0x0a,
	0x24, 0xfc, 0x14, 0xea, 0x51, 0xf2, 0x78, 0xb4, 0xd9, 0x4b, 0x39, 0x80, 0xda, 0x29, 0xe3, 0x7a,
	0xa1, 0x4b, 0x4d, 0x7f, 0x1a, 0x50, 0x8f, 0x6c, 0xef, 0x89, 0x2b, 0x86, 0x27, 0x15, 0xaa, 0xe7,
	0xe0, 0xac, 0x04, 0x72, 0x2e, 0xfb, 0x3e, 0x88, 0xfb, 0xce, 0x77, 0xf3, 0xbd, 0xea, 0x51, 0xbd,
	0x1f, 0x7e, 0x0a, 0xd4, 0xf4, 0xe3, 0x41, 0x1c, 0x40, 0x83, 0xdc, 0x11, 0xdb, 0x21, 0x63, 0x87,
	0x5d, 0x24, 0xfa, 0xad, 0x47, 0xf8, 0xb1, 0x84, 0xd1, 0x1e, 0xac, 0x89, 0x3d, 0x32, 0x1a, 0xda,
	0x15, 0xa4, 0xdd, 0xaa, 0x02, 0x95, 0x11, 0x46, 0xd0, 0x10, 0x2c, 0x14, 0x6d, 0x44, 0xf7, 0xfa,
	0xcb, 0x80, 0x75, 0x0d, 0xfc, 0x67, 0x9b, 0xcb, 0xb8, 0xfe, 0x62, 0xd6, 0xf5, 0x9f, 0x41, 0x63,
	0x40, 0x69, 0x50, 0x4c, 0xb0, 0xf7, 0xbf, 0xa1, 0xfb, 0x1e, 0xac, 0x6b, 0xf1, 0x82, 0xf1, 0xd5,
	0x20, 0x17, 0x4d, 0x2e, 0x67, 0x53, 0x7c, 0x0c, 0x75, 0x71, 0xef, 0x0f, 0xe1, 0x9a, 0x50, 0xc8,
	0x8b, 0xb7, 0xa9, 0xcc, 0x55, 0xb0, 0x8a, 0x42, 0x1c, 0x52, 0x8c, 0xa1, 0x11, 0x07, 0x59, 0x92,
	0xe8, 0x19, 0xac, 0x5b, 0x8c, 0xcf, 0xbd, 0x74, 0xaa, 0xcc, 0x8f, 0x8b, 0x78, 0x4a, 0x74, 0x6b,
	0x15, 0xf3, 0xe8, 0x7b, 0x11, 0x6a, 0x23, 0xb5, 0xb4, 0x4f, 0xcc, 0xbb, 0xb3, 0x2f, 0x19, 0x7a,
	0x0b, 0xa5, 0xe0, 0xac, 0x50, 0x2b, 0x5e, 0x68, 0xe2, 0xca, 0xcd, 0xf6, 0xa2, 0x42, 0x05, 0xc4,
	0x2b, 0xc2, 0x3f, 0x38, 0x1f, 0xcd, 0x3f, 0x79, 0x7c, 0x9a, 0x7f, 0xea, 0xd2, 0xf0, 0x0a, 0x7a,
	0x0f, 0x95, 0x88, 0xa3, 0x68, 0x2b, 0x32, 0x4c, 0x93, 0xd9, 0x34, 0xb3, 0x54, 0x61, 0x94, 0xe7,
	0x06, 0x3a, 0x81, 0x4a, 0xb4, 0x2c, 0x2d, 0x4e, 0x9a, 0x10, 0x5a, 0x9c, 0x85, 0xdd, 0xe2, 0x15,
	0x34, 0x82, 0xaa, 0xf6, 0xd6, 0xa2, 0x4e, 0x22, 0x69, 0xf2, 0x5d, 0x36, 0xb7, 0xb3, 0x95, 0x5a,
	0x4d, 0x03, 0x28, 0x87, 0x6b, 0x45, 0xf1, 0x0c, 0x52, 0x74, 0x31, 0xb7, 0x32, 0x34, 0x51, 0x41,
	0xa7, 0x00, 0xf1, 0x1e, 0x51, 0x5c, 0xfc, 0x02, 0x15, 0xcc, 0x4e, 0xa6, 0x2e, 0x0a, 0x74, 0x0d,
	0xcd, 0xac, 0x67, 0x0a, 0x3d, 0x49, 0x74, 0xb1, 0xe4, 0xf9, 0x33, 0xf7, 0xef, 0xb1, 0xd2, 0x9a,
	0xfe, 0x2c, 0x28, 0xa6, 0xff, 0x25, 0xa0, 0x47, 0x09, 0xe7, 0x85, 0xff, 0x0a, 0x73, 0x77, 0xa9,
	0x5e, 0x0b, 0xfb, 0x01, 0x56, 0xf5, 0xa7, 0x1d, 0x6d, 0xeb, 0x7b, 0x4c, 0xff, 0x2f, 0x98, 0x3b,
	0x4b, 0xb4, 0x61, 0xc0, 0x71, 0x51, 0x3e, 0x97, 0x2f, 0x7e, 0x07, 0x00, 0x00, 0xff, 0xff, 0xc8,
	0x01, 0x18, 0x67, 0xac, 0x09, 0x00, 0x00,
}
